import { EventTypes } from '@/helpers/types';

const mockEvents: EventTypes[] = [
  {
    _id: '1',
    eventName: 'Tech Conference 2025',
    eventDescription: 'A gathering of tech enthusiasts and professionals.',
    eventStartDate: '2025-05-15',
    eventStartTime: '10:00 AM',
    eventEndDate: '2025-05-15',
    eventEndTime: '5:00 PM',
    eventBanner: 'https://example.com/banner1.jpg',
    eventType: 'Conference',
    eventAddress: {
      fullAddress: '123 Tech St, New York, NY',
      latitude: 40.7128,
      longitude: -74.006,
    },
    createdBy: 'user_123',
    eventIsFeatured: true,
    eventPrice: 50,
  },
  {
    _id: '2',
    eventName: 'Music Festival 2024',
    eventDescription: 'A celebration of music with top artists.',
    eventStartDate: '2024-07-10',
    eventStartTime: '12:00 PM',
    eventEndDate: '2024-07-12',
    eventEndTime: '11:59 PM',
    eventBanner: 'https://example.com/banner2.jpg',
    eventType: 'Festival',
    eventAddress: {
      fullAddress: '456 Music Lane, Los Angeles, CA',
      latitude: 34.0522,
      longitude: -118.2437,
    },
    createdBy: 'user_456',
    eventPrice: 100,
  },
  {
    _id: '3',
    eventName: 'Startup Pitch Night',
    eventDescription: 'An opportunity for startups to showcase ideas.',
    eventStartDate: '2024-09-20',
    eventStartTime: '6:00 PM',
    eventEndDate: '2024-09-20',
    eventEndTime: '9:00 PM',
    eventBanner: 'https://example.com/banner3.jpg',
    eventType: 'Networking',
    eventAddress: {
      fullAddress: '789 Startup Rd, San Francisco, CA',
      latitude: 37.7749,
      longitude: -122.4194,
    },
    createdBy: 'user_789',
    eventPrice: 0,
  },
  {
    _id: '4',
    eventName: 'E-Sports Championship',
    eventDescription: 'Battle it out in the biggest e-sports tournament.',
    eventStartDate: '2025-01-10',
    eventStartTime: '4:00 PM',
    eventEndDate: '2025-01-15',
    eventEndTime: '11:00 PM',
    eventBanner: 'https://example.com/banner4.jpg',
    eventType: 'Gaming',
    eventAddress: {
      fullAddress: '500 Arena Ave, Dallas, TX',
      latitude: 32.7767,
      longitude: -96.797,
    },
    createdBy: 'user_321',
    eventIsFeatured: true,
    eventPrice: 25,
  },
  {
    _id: '5',
    eventName: 'Art Exhibition',
    eventDescription: 'Experience the latest contemporary art pieces.',
    eventStartDate: '2024-06-25',
    eventStartTime: '3:00 PM',
    eventEndDate: '2024-06-28',
    eventEndTime: '8:00 PM',
    eventBanner: 'https://example.com/banner5.jpg',
    eventType: 'Exhibition',
    eventAddress: {
      fullAddress: '100 Art St, Chicago, IL',
      latitude: 41.8781,
      longitude: -87.6298,
    },
    createdBy: 'user_654',
    eventPrice: 20,
  },
  {
    _id: '6',
    eventName: 'Hackathon 2024',
    eventDescription: '24-hour coding challenge for developers.',
    eventStartDate: '2024-10-05',
    eventStartTime: '9:00 AM',
    eventEndDate: '2024-10-06',
    eventEndTime: '9:00 AM',
    eventBanner: 'https://example.com/banner6.jpg',
    eventType: 'Competition',
    eventAddress: {
      fullAddress: '200 Code St, Austin, TX',
      latitude: 30.2672,
      longitude: -97.7431,
    },
    createdBy: 'user_852',
    eventPrice: 0,
  },
  {
    _id: '7',
    eventName: 'Fitness Bootcamp',
    eventDescription: 'An intensive fitness training session.',
    eventStartDate: '2024-08-15',
    eventStartTime: '7:00 AM',
    eventEndDate: '2024-08-15',
    eventEndTime: '10:00 AM',
    eventBanner: 'https://example.com/banner7.jpg',
    eventType: 'Wellness',
    eventAddress: {
      fullAddress: '300 Gym St, Miami, FL',
      latitude: 25.7617,
      longitude: -80.1918,
    },
    createdBy: 'user_963',
    eventPrice: 15,
  },
  {
    _id: '8',
    eventName: 'Food Truck Festival',
    eventDescription: 'A festival featuring food from around the world.',
    eventStartDate: '2025-02-20',
    eventStartTime: '11:00 AM',
    eventEndDate: '2025-02-22',
    eventEndTime: '8:00 PM',
    eventBanner: 'https://example.com/banner8.jpg',
    eventType: 'Food',
    eventAddress: {
      fullAddress: '400 Eatery Blvd, Portland, OR',
      latitude: 45.5051,
      longitude: -122.675,
    },
    createdBy: 'user_147',
    eventPrice: 5,
  },
  {
    _id: '9',
    eventName: 'Photography Workshop',
    eventDescription: 'Learn the art of photography with experts.',
    eventStartDate: '2024-11-18',
    eventStartTime: '2:00 PM',
    eventEndDate: '2024-11-18',
    eventEndTime: '6:00 PM',
    eventBanner: 'https://example.com/banner9.jpg',
    eventType: 'Workshop',
    eventAddress: {
      fullAddress: '500 Lens St, Seattle, WA',
      latitude: 47.6062,
      longitude: -122.3321,
    },
    createdBy: 'user_258',
    eventPrice: 30,
  },
  {
    _id: '10',
    eventName: 'Comedy Night',
    eventDescription: 'A night full of laughter with top comedians.',
    eventStartDate: '2025-03-01',
    eventStartTime: '8:00 PM',
    eventEndDate: '2025-03-01',
    eventEndTime: '11:00 PM',
    eventBanner: 'https://example.com/banner10.jpg',
    eventType: 'Entertainment',
    eventAddress: {
      fullAddress: '600 Laugh St, Boston, MA',
      latitude: 42.3601,
      longitude: -71.0589,
    },
    createdBy: 'user_369',
    eventPrice: 40,
  },
];

export default mockEvents;
